// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptoaugbnpfxeoamenfzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0b2F1Z2JucGZ4ZW9hbWVuZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MjU0MjIsImV4cCI6MjA3MDMwMTQyMn0.SsUrffwp1crmwImgZI7wcToAjKuw9G3jNr5Bw9Og6-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});